import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Router, useRouter } from 'next/router'
import { FormEvent, useState } from 'react'
import { api } from '@/lib/axios'
import logo from '../assets/logo.jpg' 
import Swal from 'sweetalert2'

const inter = Inter({ subsets: ['latin'] })
// const router= useRouter();

export default function Login() {
  const [email, setEmail] = useState('');
  const [senha, setSenha] = useState('');
  const [token, setToken] = useState(null);
  const router = useRouter();
  async function login(event: FormEvent){
      event.preventDefault()
      try {
        const response = await api.post("/usuario/login",{
          email: email, 
          senha: senha 
        })
          if(response.status === 200){  
            setEmail("")
            setSenha("") 
            router.push(`/agendamentos?token=${encodeURIComponent((response.data.id))}`)
          }
          
          setToken(response.data.id)
      } catch (error) {
        console.log(error)
        Swal.fire({
          icon: 'error',
          title: 'E-mail ou senha esta errada',
          text: 'Insira seus dados corretamente!', 
        }) 
      }
  }  
   return (
    <>
     <nav>
          <ul>
            <li><a href="/">
              <Image src={logo} className='logo' alt=''/>
              </a></li>
            <li><a href="#"></a></li>
            <li><a href="#"></a></li>
            <li><a href="#"></a></li>
            <li><a href="#"></a></li>
            
            <li><a href="#"> </a></li>
            <li><a href="/login">Login</a></li>
            <li><a href="/cadastro">Cadastro</a></li>
          </ul>
        </nav>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://curso.guilhermegulias.com/wp-content/uploads/2022/01/cropped-LOGO-NYNO-SEM-BORDA-PRA-LOGO.jpg" />
      </Head>
      <main className={styles.main}>
        <h1>Bem vindo a Piano Room</h1>
        <img src='https://curso.guilhermegulias.com/wp-content/uploads/2022/05/cropped-logo-simples-branca.png' width={200}></img>
        <form onSubmit={login} method="">
          <input type="email"    className='input' onChange={event => setEmail(event.target.value)} value={email} name="email" id="usr"  placeholder="Digite seu e-mail"/>
          <br></br>
          <input type="password" className='input' onChange={event => setSenha(event.target.value)} value={senha} name="senha" id="senha" placeholder="Digite sua senha" />
          <br></br>
          <div align="right">
            <a href="/cadastro">Nao tenho uma conta</a>
          </div>
          <div align="center">
            <input type="submit" id='enviar' value="Enviar" />
          </div>   
          <br></br> 
        </form>
        
      </main>
    </>
  ) 
  
}
